sudo: required
language: python
python:
    - 2.7
before_install:
    - sudo pip install --upgrade pip
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install --only-binary=numpy,scipy numpy scipy
script: py.test --cov=fcdiff test_fcdiff
after_success:
    - coveralls
