language: python
python:
    - 2.7
before_install:
    - pip install --user --upgrade pip
    - export PATH=$HOME/.local/bin:$PATH
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install --only-binary :all: numpy scipy
script: py.test --cov=fcdiff test_fcdiff
after_success:
    - coveralls
